spring:
  application:
    name: youtube-summarizer

app:
  cors:
    allowed-origin: ${ALLOWED_ORIGIN:*}
  media-service:
    url: ${MEDIA_SERVICE_URL:http://localhost:5001}

logging:
  level:
    com.example.youtubesummarizer: DEBUG
