AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  YouTubeSummarizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Runtime: python3.13
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          GEMINI_API_KEY:  '{{resolve:ssm:/myapp/gemini_api_key}}'
          WEBSHARE_USERNAME:  '{{resolve:ssm:/myapp/webshare_username}}'
          WEBSHARE_PASSWORD:  '{{resolve:ssm:/myapp/webshare_password}}'
          GEMINI_MODEL: gemini-2.5-flash
      Events:
        Summarize:
          Type: Api
          Properties:
            Path: /summarize
            Method: post
        Transcript:
          Type: Api
          Properties:
            Path: /transcript
            Method: get
        Process:
          Type: Api
          Properties:
            Path: /process
            Method: post
Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'